# Generated by Django 4.2.5 on 2024-01-19 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_post_query'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='position',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
